#!/bin/bash

set -e

ORIGINAL_DIR="$(pwd)"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEMATICS_PACKAGE_NAME="init-schematics"
SCHEMATICS_DIR="$SCRIPT_DIR/$SCHEMATICS_PACKAGE_NAME"
SCHEMATICS_PACKAGE_TARBALL="$SCHEMATICS_DIR/$SCHEMATICS_PACKAGE_NAME-0.0.0.tgz"

ANGULAR_APP_DIR_NAME="ui"
ANGULAR_APP_DIR="$ORIGINAL_DIR/$ANGULAR_APP_DIR_NAME"

cd $SCHEMATICS_DIR

npm install
npm run build
npm pack

cd $ORIGINAL_DIR

ng new $ANGULAR_APP_DIR_NAME

cd $ANGULAR_APP_DIR

npm install --no-save $(realpath --relative-to=$ANGULAR_APP_DIR $SCHEMATICS_PACKAGE_TARBALL)

ng g $SCHEMATICS_PACKAGE_NAME:proxy-config
ng g $SCHEMATICS_PACKAGE_NAME:app-component
ng g $SCHEMATICS_PACKAGE_NAME:spa-root
ng g $SCHEMATICS_PACKAGE_NAME:app-interceptor


